# Generated by Django 5.2.2 on 2025-06-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='key',
        ),
        migrations.RemoveField(
            model_name='templateinstance',
            name='key',
        ),
        migrations.AddField(
            model_name='template',
            name='file',
            field=models.FileField(blank=True, upload_to='templates/'),
        ),
        migrations.AddField(
            model_name='templateinstance',
            name='file',
            field=models.FileField(blank=True, upload_to='template-instances/'),
        ),
    ]
