# Generated by Django 5.2.2 on 2025-06-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_remove_template_key_remove_templateinstance_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateinstance',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templateinstance',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='templateinstance',
            name='file',
            field=models.FileField(blank=True, upload_to='templates-instances/'),
        ),
    ]
