# Generated by Django 5.2.2 on 2025-06-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_templateinstance_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateinstance',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
