# Generated by Django 5.2.2 on 2025-06-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_alter_templateinstance_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['template_type', 'name']},
        ),
        migrations.AddField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='template',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('paystub', 'Paystub'), ('w2', 'W-2 Form'), ('1099', '1099 Form'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(upload_to='system-templates/'),
        ),
        migrations.AlterField(
            model_name='templateinstance',
            name='file',
            field=models.FileField(blank=True, upload_to='template-instances/'),
        ),
    ]
