# Generated by Django 5.2.2 on 2025-06-30 10:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_alter_template_options_template_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='preview_file',
            field=models.FileField(blank=True, help_text='PDF template for preview generation', null=True, upload_to='system-templates/previews/'),
        ),
        migrations.CreateModel(
            name='TemplatePreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='template-previews/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='templates.template')),
            ],
        ),
    ]
